[features]
seeds = false
skip-lint = false
[programs.localnet]
copy_invest = "Gm4SieQBUrZ1PtPY4Vubvzx2goyZa42nc2Yvmbc8hkxT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/cot/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
